version: '3.8'

services:
  terminal-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dify-terminal-runner
    image: dify-terminal-runner:0.2.0

    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - SESSIONS_DIR=/app/sessions
      - LOG_LEVEL=INFO

    # Volume mounts - persist session data
    volumes:
      - ./sessions:/app/sessions:rw
      - ./main.py:/app/main.py:ro
      - ./executor.py:/app/executor.py:ro

    # Network configuration
    # Uncomment if you need to expose API endpoint
    # ports:
    #   - "5000:5000"

    # Resource limits (optional, can be adjusted)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'
    #       memory: 2G
    #     reservations:
    #       cpus: '0.5'
    #       memory: 512M

    # Restart policy
    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

    # Command override (optional)
    # Uncomment to run in daemon mode or custom command
    # command: python -m main

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Networks (optional)
networks:
  default:
    name: dify-plugin-network
    driver: bridge

# Volumes (optional, for persistent storage)
volumes:
  sessions-data:
    driver: local
